# Guide to using CAST_panel

Here is a Jupyter Notebook that simultaneously provides a guide to using the CAST_panel package, as well as reproducing the results in the paper: [FILL ME HERE]

In [1]:
import pandas as pd
import numpy as np
import CAST

## Uninsurance rates

In [2]:
# loads the treatment
treat = pd.read_csv("sample_data/expansion.csv")
adopt_year = treat["ADOPTION"]

uninsurance_rates = pd.read_csv("sample_data/uninsurance_rates.csv", index_col = 0)

In [3]:
treat.head()

  STATE  ADOPTION       DATE
0    AL      2025   1/1/2025
1    AK      2016   9/1/2015
2    AZ      2014   1/1/2014
3    AR      2014   1/1/2014
4    CA      2014   1/1/2014

In [4]:
uninsurance_rates.head() # our observation matrix

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2021,2022
Alabama,0.16,0.16,0.17,0.16,0.15,0.16,0.14,0.12,0.11,0.11,0.122,0.116,0.120,0.104
Alaska,0.22,0.22,0.19,0.22,0.22,0.20,0.19,0.16,0.16,0.16,0.135,0.129,0.121,0.123
Arizona,0.21,0.20,0.20,0.20,0.20,0.20,0.16,0.13,0.12,0.12,0.127,0.134,0.128,0.126
Arkansas,0.21,0.19,0.20,0.20,0.19,0.19,0.14,0.11,0.09,0.10,0.099,0.109,0.110,0.102
California,0.20,0.20,0.21,0.20,0.20,0.19,0.14,0.10,0.08,0.08,0.082,0.090,0.081,0.075

In order to run the method, we need to provide a vector that indicates the "index of treatment", i.e. from which column in the observation matrix did treatment begin. 

The following piece of code constucts the treatment index: it constructs a pandas Series that is consistent with the rows of the observation matrix, and each entry indicates the column for which treatment began in the matrix.

In [5]:
treat_index = adopt_year - 2008
treat_index.head()

0    17
1     8
2     6
3     6
4     6
Name: ADOPTION, dtype: int64

Alabama corresponds with row 0, and 17 is larger than the number of columns indicating that it has never adopted the treatment. Alaska corresponds to row 1, and its value 8 indicates that it adopted treatment in 2008 + 8 = 2016 (more precisely, September of 2015 which we rounded to 2016).

However our observation matrix is missing 2020 as an observation, so we have to hack around it to ensure that states that enacted the expansion after it has the correct index. We also need to ensure that the treatment value is equal to the number of columns in the matrix if a unit never undergoes treatment

In [6]:
treat_index[treat_index >= 13] -= 1 
treat_index = treat_index.to_list()
# makes it such that everything that began in 2020 is pushed further by a year

The treat_index variable needs to be a list where the i^th entry indicates from which column in the observation matrix did treatment for the i^th row begin.

In [7]:
treat_index

[16,
 8,
 6,
 6,
 6,
 6,
 6,
 6,
 16,
 16,
 6,
 12,
 6,
 7,
 6,
 16,
 6,
 9,
 11,
 6,
 6,
 6,
 6,
 16,
 13,
 8,
 12,
 6,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 13,
 6,
 7,
 6,
 16,
 15,
 16,
 16,
 12,
 6,
 11,
 6,
 6,
 16,
 16]

We have implemented a helper method that computes the singular values of the control matrix to aid in rank selection. It takes in both the observation matrix and the treatment index as arguments. As a whole, our library deals with numpy arrays.

In [8]:
print(CAST.rank_selection(uninsurance_rates.values, treat_index))

{'singular_values': array([2.05367718, 0.08315907, 0.04581451, 0.03229862, 0.02982912,
       0.02389201, 0.01775155, 0.01329282]), 'broken_stick': 1}

Based on the singular values, we pick to use a rank one matrix for our method.

In [9]:
uninsurance_CAST = CAST.method(uninsurance_rates.values, treat_index, rank = 1)
uninsurance_sigeffects = uninsurance_CAST.get_significant_effects()
uninsurance_sigeffects.index = uninsurance_rates.columns[6:]
uninsurance_sigeffects

      Positive effects  Negative effects  Null effects  Number treatment
2014               1.0              23.0           2.0              26.0
2015               1.0              28.0           0.0              29.0
2016               2.0              28.0           1.0              31.0
2017               2.0              28.0           2.0              32.0
2018               1.0              30.0           1.0              32.0
2019               0.0              29.0           5.0              34.0
2021               1.0              36.0           0.0              37.0
2022               0.0              36.0           3.0              39.0

To get the treatment effects, we can use the following method:

In [10]:
uninsurance_effects = uninsurance_CAST.get_treatment_effects()
pd.DataFrame(uninsurance_effects[0], index = uninsurance_rates.index, 
                 columns = uninsurance_rates.columns).head()

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2021,2022
Alabama,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Alaska,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.014439,0.007597,-0.019201,-0.029877,-0.033441,-0.018964
Arizona,0.0,0.0,0.0,0.0,0.0,0.0,-0.010076,-0.017087,-0.017507,-0.023963,-0.018662,-0.015915,-0.017735,-0.007782
Arkansas,0.0,0.0,0.0,0.0,0.0,0.0,-0.025916,-0.033490,-0.044144,-0.040443,-0.043100,-0.037249,-0.032171,-0.028510
California,0.0,0.0,0.0,0.0,0.0,0.0,-0.028744,-0.045936,-0.056430,-0.062837,-0.062522,-0.058742,-0.063595,-0.057735

In [11]:
# this is a matrix indicating which entries are controls
pd.DataFrame(uninsurance_effects[1], index = uninsurance_rates.index, 
                 columns = uninsurance_rates.columns).head()

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2021,2022
Alabama,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
Alaska,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
Arizona,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Arkansas,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
California,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
# we can also report the standard errors per entry
pd.DataFrame(uninsurance_CAST.get_std_errors(), index = uninsurance_rates.index, 
                 columns = uninsurance_rates.columns).head()

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2021,2022
Alabama,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Alaska,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.003414,0.003666,0.003380,0.003653,0.003532,0.003942
Arizona,0.0,0.0,0.0,0.0,0.0,0.0,0.002083,0.001727,0.001887,0.002122,0.001591,0.001944,0.001861,0.002716
Arkansas,0.0,0.0,0.0,0.0,0.0,0.0,0.002443,0.002053,0.002143,0.002367,0.001938,0.002242,0.002156,0.002857
California,0.0,0.0,0.0,0.0,0.0,0.0,0.001543,0.001233,0.001507,0.001754,0.001051,0.001499,0.001422,0.002468

We also provide functionality for computing the average treatment effect on the treated units for each year, as well as estimates for their standard errors.

In [13]:
# first is the average values, and the second is the standard error estimates
ATET, se_ATET = uninsurance_CAST.get_average_effect()

ATET_values = {"ATET" : ATET, "se" : se_ATET}
ATET_df = pd.DataFrame(ATET_values, index = uninsurance_rates.columns[6:])
ATET_df

          ATET        se
2014 -0.017300  0.000922
2015 -0.022789  0.000688
2016 -0.024466  0.000984
2017 -0.026775  0.001188
2018 -0.028769  0.000525
2019 -0.025996  0.000944
2021 -0.028613  0.000885
2022 -0.022443  0.001797

We also allow the average effects argument to take in weights to compute any sort of weighted treatment effects, along with their standard errors.

In [14]:
# loads the pouplation data
pop_df = pd.read_csv("sample_data/population.csv", index_col = 0)
# making sure its aligned with the uninsurance_rates observations
pop_df = pop_df[uninsurance_rates.columns].reindex(uninsurance_rates.index)
pop_df.head()

,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2021,2022
Alabama,4718206.0,4757938.0,4785298,4799642,4816632,4831586,4843737,4854803,4866824,4877989,4891628,4907965,5031864,5050380
Alaska,687455.0,698895.0,713985,722349,730810,737626,737075,738430,742575,740983,736624,733603,732964,734923
Arizona,6280362.0,6343154.0,6413737,6473416,6556344,6634690,6732873,6832810,6944767,7048088,7164228,7291843,7186683,7272487
Arkansas,2874554.0,2896843.0,2921606,2941038,2952876,2960459,2968759,2979732,2991815,3003855,3012161,3020985,3014348,3028443
California,36604337.0,36961229.0,37349363,37636311,37944551,38253768,38586706,38904296,39149186,39337785,39437463,39437610,39503200,39145060

In [15]:
# the weights must be a numpy array, the num_treated_renorm argument indicates to
# normalize all the weights such that they sum up to one for the treated units,
# by default it is true
pop_ATET, se_pop_ATET = uninsurance_CAST.get_average_effect(weights = pop_df.values, 
                                                                num_treated_renorm = False)

pop_ATET_values = {"ATET" : pop_ATET, "se" : se_pop_ATET}
pop_ATET_df = pd.DataFrame(pop_ATET_values, index = uninsurance_rates.columns[6:])
pop_ATET_df

              ATET             se
2014 -3.080816e+06  174132.574724
2015 -4.954703e+06  144598.100664
2016 -5.849858e+06  205123.753820
2017 -6.633449e+06  254322.147545
2018 -6.848940e+06  110989.119241
2019 -6.651022e+06  212763.572543
2021 -7.504618e+06  207468.916971
2022 -6.493026e+06  438264.196987

# Health expenditures

In [18]:
expenditures = pd.read_csv("sample_data/stateexp_percapita.csv", index_col = 0)
expenditures.head()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
STATE,,,,,,,,,,,,,,,,,,,,,
Alabama,2347.617669,2377.656719,2191.630568,2183.217420,2223.792242,4801.517789,5040.202152,5660.369283,2871.642315,2625.296925,...,3114.298286,3227.260274,3254.920951,3313.865470,3443.017194,3578.972072,3715.185418,3953.037388,3834.960563,4247.601171
Alaska,0.000000,0.000000,5749.318504,6441.872014,6898.371875,8721.845547,10047.356590,12550.345436,13589.253115,13700.198170,...,12788.323622,11794.864837,14208.029628,9097.128236,8055.515444,9063.104107,10095.514877,9742.080371,9300.593208,10605.192653
Arizona,2290.534447,2389.505065,2590.500264,2283.651316,2630.935439,2650.418893,2834.068734,2610.300371,2774.840049,2678.320596,...,2344.088119,3330.376200,3824.341669,3922.233820,2913.272365,3094.541380,3149.272413,7771.705828,7034.687477,8254.228052
Arkansas,2831.173738,2972.613392,3181.564395,3242.061002,3432.912319,3613.681939,3792.312673,4043.669809,4206.913490,4407.556778,...,5194.870120,5477.069712,5607.752644,5555.011009,5761.926115,5837.373352,5944.094977,6030.314249,6211.956947,6532.399652
California,2496.882942,2795.345565,2845.275485,3028.920047,2929.704630,3003.075002,3320.599907,3585.293379,3771.820809,3311.199419,...,3685.937553,3701.015578,4120.239060,4092.268994,4216.811750,4496.129885,5153.531439,5285.754184,5735.976225,6915.158260

In [48]:
treat_index = adopt_year - 2000
treat_index = treat_index.to_list()

print(CAST.rank_selection(expenditures.values, treat_index))

{'singular_values': array([59929.07160213,  5525.18226946,  3986.05229358,  1691.5044982 ,
        1267.62880648,  1175.57179881,   879.08639218,   608.08689983,
         525.57974705]), 'broken_stick': 1}

In [111]:
expend_CAST = CAST.method(expenditures.values, treat_index, rank = 3)
expend_sigeffects = expend_CAST.get_significant_effects()
expend_sigeffects.index = expenditures.columns[-9:]
expend_sigeffects

      Positive effects  Negative effects  Null effects  Number treatment
2014              10.0               6.0          10.0              26.0
2015               6.0               4.0          19.0              29.0
2016               7.0               7.0          17.0              31.0
2017               6.0               5.0          21.0              32.0
2018               9.0               6.0          17.0              32.0
2019               9.0              10.0          15.0              34.0
2020              14.0               7.0          15.0              36.0
2021              19.0               8.0          10.0              37.0
2022              16.0              11.0          12.0              39.0

In [112]:
# first is the average values, and the second is the standard error estimates
ATET, se_ATET = expend_CAST.get_average_effect()

ATET_values = {"ATET" : ATET, "se" : se_ATET}
ATET_df = pd.DataFrame(ATET_values, index = expenditures.columns[-9:])
ATET_df

            ATET         se
2014   98.921934  53.887280
2015  139.471423  55.165686
2016   78.783908  57.178851
2017  -92.445694  67.341482
2018   29.156311  66.383097
2019 -120.132579  89.748709
2020  175.251414  65.171699
2021  264.683816  48.630490
2022  128.028141  60.768920

# Infant mortality rates

In [115]:
treat = adopt_year - 2001
treat_index = treat.to_list()

mortality_rates_infant = pd.read_csv("sample_data/mortality_rates_infant_wind3.csv", index_col = 0)

In [116]:
inf_mort_CAST = CAST.method(mortality_rates_infant, treat_index, rank = 3)

print(inf_mort_CAST.get_significant_effects())

InvalidIndexError: (array([ 0, 42, 41, 40, 39, 35, 26, 48, 23, 15, 24, 49,  8,  9, 43, 11, 18,
       45, 17, 25,  1, 37, 13, 28, 38,  4,  3, 16, 36, 12, 44, 46, 47,  2,
        5, 32, 33, 14, 31, 10, 29, 27,  6,  7, 22, 21, 20, 19, 34, 30]), slice(None, None, None))

In [36]:
# loads the treatment
treat = pd.read_csv("sample_data/expansion.csv")
adopt_year = treat["ADOPTION"]

mortality_rates_infant = np.genfromtxt("sample_data/mortality_rates_infant_wind3.csv", delimiter=",")
mortality_rates_infant = mortality_rates_infant[1:,1:]


pop_df = pd.read_csv("sample_data/births_1999-2020_wind3.csv")

if pop_df.shape[0] == 51:
    pop_df = pop_df.drop([8])

years = np.arange(2001, 2021)
treat = adopt_year - 2001
treat_index = treat.to_list()



print(CAST.rank_selection(mortality_rates_infant, treat_index))

inf_mort_CAST = CAST.method(mortality_rates_infant, treat_index, rank = 3)


print(inf_mort_CAST.get_significant_effects())

{'singular_values': array([9275.94659706,  269.30981323,  166.71897289,  115.1514331 ,
         62.48948766,   51.08276807,   32.08624455]), 'broken_stick': 1}
   Positive effects  Negative effects  Null effects  Number treatment
0               5.0              12.0           9.0              26.0
1               6.0              17.0           6.0              29.0
2               5.0              15.0          11.0              31.0
3               5.0              16.0          11.0              32.0
4               4.0              18.0          10.0              32.0
5               3.0              22.0           9.0              34.0
6               6.0              20.0          10.0              36.0

In [38]:
mortality_rates_infant

array([[ 986.86666667,  947.96666667,  910.        ,  894.76666667,
         908.66666667,  923.43333333,  971.2       ,  972.26666667,
         938.23333333,  888.86666667,  842.36666667,  851.5       ,
         846.96666667,  871.1       ,  867.46666667,  888.9       ,
         841.43333333,  794.96666667,  750.8       ,  740.4       ],
       [ 721.96666667,  706.        ,  704.63333333,  660.8       ,
         674.36666667,  681.6       ,  676.03333333,  679.86666667,
         663.6       ,  570.6       ,  492.33333333,  431.63333333,
         483.83333333,  579.66666667,  637.03333333,  635.3       ,
         588.43333333,  547.56666667,  525.1       ,  516.16666667],
       [ 715.3       ,  699.13333333,  679.5       ,  682.2       ,
         701.43333333,  704.73333333,  715.53333333,  698.26666667,
         682.2       ,  634.5       ,  607.16666667,  587.3       ,
         565.63333333,  578.76666667,  565.2       ,  561.43333333,
         536.8       ,  535.86666667,  537.1       ,  520.3       ],
       [ 841.83333333,  849.76666667,  851.06666667,  854.36666667,
         841.03333333,  842.86666667,  822.        ,  801.1       ,
         768.53333333,  752.6       ,  758.1       ,  732.3       ,
         738.13333333,  742.23333333,  764.46666667,  786.8       ,
         801.53333333,  794.5       ,  751.7       ,  726.36666667],
       [ 571.76666667,  566.6       ,  546.93333333,  547.1       ,
         547.03333333,  548.7       ,  554.76666667,  544.96666667,
         537.1       ,  514.23333333,  494.96666667,  467.83333333,
         461.16666667,  446.6       ,  444.13333333,  425.        ,
         416.3       ,  405.4       ,  403.33333333,  391.86666667],
       [ 645.66666667,  623.73333333,  612.46666667,  637.56666667,
         650.6       ,  640.1       ,  631.16666667,  625.66666667,
         641.96666667,  628.36666667,  593.63333333,  528.        ,
         499.06666667,  475.53333333,  478.23333333,  468.06666667,
         453.86666667,  451.1       ,  452.        ,  463.6       ],
       [ 630.23333333,  640.66666667,  601.4       ,  584.06666667,
         566.2       ,  601.5       ,  642.43333333,  647.03333333,
         616.7       ,  564.46666667,  530.83333333,  515.8       ,
         491.93333333,  480.86666667,  492.9       ,  502.46666667,
         494.06666667,  450.86666667,  437.96666667,  427.06666667],
       [ 944.1       ,  986.9       ,  977.3       ,  917.53333333,
         929.66666667,  901.43333333,  866.3       ,  846.        ,
         826.16666667,  832.2       ,  832.        ,  809.36666667,
         743.5       ,  673.23333333,  725.46666667,  792.33333333,
         789.63333333,  681.3       ,  620.4       ,  585.5       ],
       [ 754.36666667,  749.03333333,  751.86666667,  753.53333333,
         752.1       ,  753.3       ,  758.96666667,  758.33333333,
         740.3       ,  714.53333333,  678.66666667,  641.16666667,
         622.        ,  613.86666667,  622.03333333,  621.8       ,
         615.93333333,  605.2       ,  600.73333333,  584.46666667],
       [ 885.8       ,  899.63333333,  882.26666667,  889.2       ,
         870.96666667,  866.36666667,  850.6       ,  841.76666667,
         814.23333333,  752.1       ,  701.73333333,  646.13333333,
         657.33333333,  683.56666667,  740.36666667,  762.86666667,
         749.53333333,  720.8       ,  704.63333333,  669.96666667],
       [ 774.6       ,  771.53333333,  729.86666667,  710.16666667,
         674.7       ,  610.7       ,  641.56666667,  616.63333333,
         622.6       ,  620.13333333,  611.66666667,  578.33333333,
         579.43333333,  540.43333333,  556.56666667,  535.46666667,
         559.56666667,  594.86666667,  564.        ,  555.26666667],
       [ 695.2       ,  671.03333333,  629.53333333,  630.3       ,
         630.6       ,  644.86666667,  663.86666667,  659.36666667,
         608.46666667,  539.63333333,  502.9       ,  506.93333333,
         538.93333333,  557.6       ,  528.83333333,  537.36666667,
         503.06666667,  509.63333333,  457.23333333,  477.46666667],
       [ 858.4       ,  812.96666667,  780.33333333,  777.9       ,
         784.73333333,  774.03333333,  754.53333333,  744.23333333,
         724.4       ,  716.9       ,  679.56666667,  655.33333333,
         625.3       ,  636.46666667,  626.93333333,  640.46666667,
         615.43333333,  623.6       ,  594.93333333,  572.26666667],
       [ 790.93333333,  778.46666667,  769.16666667,  790.63333333,
         804.13333333,  814.3       ,  801.93333333,  762.3       ,
         755.4       ,  751.2       ,  772.16666667,  731.9       ,
         719.93333333,  704.        ,  723.73333333,  729.53333333,
         733.        ,  719.5       ,  690.3       ,  666.23333333],
       [ 601.06666667,  584.9       ,  552.23333333,  536.7       ,
         541.4       ,  526.2       ,  538.1       ,  541.3       ,
         520.96666667,  499.2       ,  470.46666667,  498.23333333,
         478.76666667,  485.7       ,  445.66666667,  506.26666667,
         515.66666667,  541.9       ,  507.7       ,  476.53333333],
       [ 732.63333333,  725.83333333,  714.96666667,  711.43333333,
         722.8       ,  745.83333333,  772.33333333,  763.33333333,
         750.03333333,  686.53333333,  646.73333333,  625.2       ,
         628.9       ,  629.26666667,  615.13333333,  601.        ,
         588.33333333,  605.8       ,  599.13333333,  628.53333333],
       [ 708.1       ,  692.76666667,  676.03333333,  708.03333333,
         689.53333333,  714.56666667,  713.6       ,  718.46666667,
         694.63333333,  695.46666667,  672.93333333,  677.        ,
         665.6       ,  698.4       ,  683.36666667,  690.9       ,
         666.56666667,  637.66666667,  579.43333333,  570.43333333],
       [ 966.13333333,  988.06666667,  989.1       , 1014.03333333,
         986.43333333, 1070.16666667, 1030.86666667, 1008.96666667,
         905.83333333,  847.5       ,  821.76666667,  796.5       ,
         840.13333333,  832.9       ,  825.13333333,  794.93333333,
         763.6       ,  752.06666667,  752.23333333,  773.06666667],
       [ 531.26666667,  512.        ,  512.26666667,  495.03333333,
         580.66666667,  628.63333333,  649.13333333,  597.        ,
         574.06666667,  544.86666667,  580.73333333,  615.83333333,
         676.56666667,  684.6       ,  675.8       ,  631.46666667,
         595.53333333,  560.4       ,  541.46666667,  550.03333333],
       [ 826.46666667,  791.8       ,  803.9       ,  817.4       ,
         812.7       ,  809.8       ,  800.5       ,  827.73333333,
         797.93333333,  755.43333333,  705.86666667,  673.76666667,
         658.66666667,  650.7       ,  658.46666667,  661.9       ,
         656.66666667,  635.9       ,  612.33333333,  587.43333333],
       [ 506.9       ,  494.73333333,  500.13333333,  498.66666667,
         510.56666667,  510.4       ,  515.23333333,  512.        ,
         519.6       ,  499.6       ,  465.16666667,  433.26666667,
         417.66666667,  420.2       ,  419.46666667,  413.76666667,
         392.43333333,  388.1       ,  378.26666667,  382.56666667],
       [ 825.26666667,  821.23333333,  826.86666667,  814.96666667,
         812.03333333,  773.36666667,  787.93333333,  768.13333333,
         771.06666667,  740.23333333,  712.23333333,  693.33333333,
         691.96666667,  692.13333333,  674.23333333,  651.96666667,
         656.46666667,  645.73333333,  643.        ,  635.26666667],
       [ 581.76666667,  553.46666667,  518.63333333,  499.6       ,
         490.46666667,  511.53333333,  540.3       ,  567.96666667,
         543.46666667,  505.5       ,  463.2       ,  479.1       ,
         499.73333333,  509.73333333,  509.3       ,  509.56666667,
         498.16666667,  493.6       ,  472.8       ,  447.7       ],
       [1079.53333333, 1079.96666667, 1070.46666667, 1056.56666667,
        1089.73333333, 1110.1       , 1121.73333333, 1070.73333333,
        1023.9       ,  997.93333333,  976.        ,  918.53333333,
         917.6       ,  886.93333333,  911.13333333,  882.        ,
         892.43333333,  865.86666667,  877.7       ,  862.23333333],
       [ 766.66666667,  782.26666667,  803.33333333,  810.8       ,
         783.43333333,  769.56666667,  770.1       ,  757.36666667,
         743.53333333,  710.4       ,  681.33333333,  663.3       ,
         660.86666667,  650.56666667,  643.36666667,  642.96666667,
         644.43333333,  638.2       ,  622.26666667,  597.83333333],
       [ 661.6       ,  686.26666667,  709.86666667,  634.8       ,
         620.7       ,  594.23333333,  653.66666667,  649.63333333,
         640.93333333,  623.76666667,  590.16666667,  592.76666667,
         590.3       ,  576.06666667,  575.33333333,  572.93333333,
         558.33333333,  511.46666667,  476.06666667,  473.1       ],
       [ 719.26666667,  725.4       ,  655.03333333,  649.7       ,
         600.43333333,  607.36666667,  614.63333333,  607.03333333,
         600.36666667,  543.83333333,  543.46666667,  512.23333333,
         518.86666667,  509.86666667,  550.26666667,  575.03333333,
         582.26666667,  579.86666667,  539.66666667,  540.4       ],
       [ 644.53333333,  623.9       ,  586.6       ,  612.23333333,
         608.46666667,  641.96666667,  646.86666667,  630.6       ,
         600.7       ,  562.93333333,  563.2       ,  523.26666667,
         520.56666667,  525.26666667,  545.46666667,  551.26666667,
         554.06666667,  579.        ,  580.03333333,  534.53333333],
       [ 520.66666667,  487.56666667,  417.63333333,  476.86666667,
         482.33333333,  544.2       ,  539.83333333,  502.46666667,
         478.3       ,  428.46666667,  456.        ,  425.6       ,
         475.3       ,  458.43333333,  456.76666667,  396.43333333,
         391.96666667,  373.7       ,  355.83333333,  363.4       ],
       [ 675.96666667,  638.2       ,  608.3       ,  575.        ,
         562.33333333,  568.2       ,  562.46666667,  573.03333333,
         553.06666667,  532.66666667,  512.4       ,  483.73333333,
         466.33333333,  439.96666667,  447.4       ,  438.83333333,
         441.7       ,  414.93333333,  421.13333333,  404.63333333],
       [ 678.86666667,  655.83333333,  620.73333333,  622.13333333,
         614.7       ,  624.43333333,  624.5       ,  610.3       ,
         582.16666667,  551.8       ,  531.63333333,  576.13333333,
         566.9       ,  570.23333333,  516.76666667,  545.        ,
         556.33333333,  575.46666667,  557.56666667,  541.13333333],
       [ 644.76666667,  627.03333333,  608.96666667,  620.6       ,
         616.7       ,  607.16666667,  594.7       ,  582.66666667,
         570.03333333,  554.1       ,  533.06666667,  517.1       ,
         500.96666667,  487.        ,  468.9       ,  455.66666667,
         450.1       ,  440.53333333,  433.36666667,  413.3       ],
       [ 910.36666667,  869.66666667,  836.86666667,  853.83333333,
         880.2       ,  879.53333333,  869.2       ,  846.46666667,
         834.83333333,  777.6       ,  737.23333333,  714.8       ,
         714.6       ,  715.1       ,  714.3       ,  722.56666667,
         719.03333333,  698.76666667,  685.33333333,  676.03333333],
       [ 799.96666667,  788.03333333,  769.53333333,  660.16666667,
         649.06666667,  595.53333333,  657.73333333,  652.4       ,
         659.23333333,  637.3       ,  662.1       ,  687.7       ,
         671.06666667,  621.1       ,  633.16666667,  632.8       ,
         596.26666667,  536.06666667,  566.5       ,  605.36666667],
       [ 799.83333333,  789.2       ,  787.33333333,  792.73333333,
         807.33333333,  810.6       ,  813.1       ,  790.83333333,
         783.26666667,  778.86666667,  776.66666667,  774.        ,
         767.        ,  739.83333333,  723.06666667,  720.36666667,
         727.9       ,  720.33333333,  705.26666667,  683.23333333],
       [ 842.1       ,  823.56666667,  792.83333333,  818.9       ,
         818.6       ,  830.8       ,  846.66666667,  818.7       ,
         807.76666667,  774.7       ,  763.8       ,  752.93333333,
         726.33333333,  765.2       ,  747.63333333,  763.7       ,
         737.5       ,  731.06666667,  718.4       ,  660.8       ],
       [ 570.13333333,  564.93333333,  561.26666667,  570.03333333,
         575.03333333,  578.23333333,  585.16666667,  564.1       ,
         534.23333333,  501.73333333,  474.16666667,  488.96666667,
         491.03333333,  513.66666667,  503.96666667,  488.96666667,
         485.86666667,  448.36666667,  454.63333333,  419.93333333],
       [ 733.13333333,  740.2       ,  745.3       ,  750.43333333,
         741.4       ,  753.93333333,  768.2       ,  768.73333333,
         749.36666667,  736.96666667,  705.7       ,  697.06666667,
         671.73333333,  650.7       ,  618.73333333,  602.73333333,
         608.5       ,  604.06666667,  595.73333333,  574.96666667],
       [ 639.03333333,  688.9       ,  705.2       ,  649.66666667,
         634.23333333,  615.53333333,  691.86666667,  664.76666667,
         665.93333333,  655.43333333,  666.73333333,  672.83333333,
         646.36666667,  580.13333333,  546.3       ,  523.        ,
         578.7       ,  559.26666667,  562.06666667,  495.26666667],
       [ 947.76666667,  903.53333333,  885.03333333,  904.43333333,
         919.63333333,  931.        ,  902.73333333,  847.7       ,
         788.86666667,  745.4       ,  717.2       ,  734.13333333,
         717.06666667,  694.23333333,  674.8       ,  678.43333333,
         677.26666667,  686.16666667,  688.9       ,  689.43333333],
       [ 753.03333333,  669.43333333,  717.73333333,  742.83333333,
         761.46666667,  768.93333333,  711.73333333,  750.23333333,
         734.76666667,  747.03333333,  669.        ,  742.73333333,
         727.7       ,  714.1       ,  656.06666667,  597.43333333,
         658.16666667,  609.3       ,  670.83333333,  643.83333333],
       [ 877.93333333,  927.86666667,  923.7       ,  928.66666667,
         921.13333333,  907.23333333,  902.36666667,  867.43333333,
         838.03333333,  814.4       ,  785.9       ,  759.03333333,
         721.93333333,  712.03333333,  701.        ,  717.96666667,
         727.46666667,  727.96666667,  717.56666667,  678.13333333],
       [ 625.6       ,  627.03333333,  645.06666667,  661.9       ,
         671.36666667,  663.96666667,  668.5       ,  654.96666667,
         643.9       ,  629.86666667,  595.1       ,  579.96666667,
         569.4       ,  590.73333333,  590.93333333,  581.5       ,
         565.4       ,  550.4       ,  545.66666667,  534.8       ],
       [ 521.53333333,  547.46666667,  536.83333333,  550.03333333,
         513.63333333,  518.86666667,  515.63333333,  528.66666667,
         527.06666667,  510.26666667,  524.23333333,  511.66666667,
         526.1       ,  506.2       ,  509.        ,  512.36666667,
         531.93333333,  536.8       ,  529.16666667,  520.73333333],
       [ 581.83333333,  529.7       ,  496.6       ,  471.53333333,
         546.2       ,  573.86666667,  590.73333333,  520.46666667,
         531.5       ,  506.96666667,  523.06666667,  463.6       ,
         462.46666667,  448.93333333,  449.23333333,  415.13333333,
         414.4       ,  471.36666667,  454.7       ,  417.13333333],
       [ 750.13333333,  751.        ,  769.83333333,  771.83333333,
         776.6       ,  761.76666667,  776.9       ,  755.66666667,
         756.5       ,  719.06666667,  712.86666667,  680.06666667,
         652.5       ,  615.16666667,  596.26666667,  586.16666667,
         589.1       ,  578.16666667,  576.8       ,  567.03333333],
       [ 542.26666667,  562.66666667,  571.33333333,  565.46666667,
         544.83333333,  514.66666667,  492.4       ,  503.63333333,
         507.23333333,  495.03333333,  460.7       ,  471.63333333,
         469.2       ,  471.23333333,  458.7       ,  454.63333333,
         429.13333333,  415.56666667,  411.16666667,  429.3       ],
       [ 756.86666667,  804.53333333,  786.83333333,  793.53333333,
         761.66666667,  762.33333333,  763.2       ,  739.36666667,
         757.        ,  754.93333333,  734.13333333,  722.26666667,
         735.86666667,  743.26666667,  722.63333333,  699.26666667,
         695.33333333,  708.66666667,  683.06666667,  701.1       ],
       [ 695.26666667,  693.03333333,  687.13333333,  649.5       ,
         645.2       ,  643.66666667,  658.86666667,  666.16666667,
         650.66666667,  627.7       ,  600.06666667,  587.36666667,
         601.46666667,  586.13333333,  588.1       ,  595.2       ,
         615.36666667,  626.1       ,  608.06666667,  589.73333333],
       [ 653.33333333,  651.6       ,  617.36666667,  718.7       ,
         723.83333333,  772.4       ,  719.76666667,  719.93333333,
         668.9       ,  644.23333333,  626.43333333,  609.23333333,
         544.7       ,  542.83333333,  537.66666667,  550.4       ,
         478.5       ,  480.16666667,  546.93333333,  567.73333333]])

In [37]:
treat_index

[24,
 15,
 13,
 13,
 13,
 13,
 13,
 13,
 24,
 24,
 13,
 19,
 13,
 14,
 13,
 24,
 13,
 16,
 18,
 13,
 13,
 13,
 13,
 24,
 21,
 15,
 20,
 13,
 14,
 13,
 13,
 13,
 13,
 13,
 13,
 21,
 13,
 14,
 13,
 24,
 23,
 24,
 24,
 19,
 13,
 18,
 13,
 13,
 24,
 24]

In [17]:
mortality_rates_infant

array([[ 986.86666667,  947.96666667,  910.        ,  894.76666667,
         908.66666667,  923.43333333,  971.2       ,  972.26666667,
         938.23333333,  888.86666667,  842.36666667,  851.5       ,
         846.96666667,  871.1       ,  867.46666667,  888.9       ,
         841.43333333,  794.96666667,  750.8       ,  740.4       ],
       [ 721.96666667,  706.        ,  704.63333333,  660.8       ,
         674.36666667,  681.6       ,  676.03333333,  679.86666667,
         663.6       ,  570.6       ,  492.33333333,  431.63333333,
         483.83333333,  579.66666667,  637.03333333,  635.3       ,
         588.43333333,  547.56666667,  525.1       ,  516.16666667],
       [ 715.3       ,  699.13333333,  679.5       ,  682.2       ,
         701.43333333,  704.73333333,  715.53333333,  698.26666667,
         682.2       ,  634.5       ,  607.16666667,  587.3       ,
         565.63333333,  578.76666667,  565.2       ,  561.43333333,
         536.8       ,  535.86666667,  537.1       ,  520.3       ],
       [ 841.83333333,  849.76666667,  851.06666667,  854.36666667,
         841.03333333,  842.86666667,  822.        ,  801.1       ,
         768.53333333,  752.6       ,  758.1       ,  732.3       ,
         738.13333333,  742.23333333,  764.46666667,  786.8       ,
         801.53333333,  794.5       ,  751.7       ,  726.36666667],
       [ 571.76666667,  566.6       ,  546.93333333,  547.1       ,
         547.03333333,  548.7       ,  554.76666667,  544.96666667,
         537.1       ,  514.23333333,  494.96666667,  467.83333333,
         461.16666667,  446.6       ,  444.13333333,  425.        ,
         416.3       ,  405.4       ,  403.33333333,  391.86666667],
       [ 645.66666667,  623.73333333,  612.46666667,  637.56666667,
         650.6       ,  640.1       ,  631.16666667,  625.66666667,
         641.96666667,  628.36666667,  593.63333333,  528.        ,
         499.06666667,  475.53333333,  478.23333333,  468.06666667,
         453.86666667,  451.1       ,  452.        ,  463.6       ],
       [ 630.23333333,  640.66666667,  601.4       ,  584.06666667,
         566.2       ,  601.5       ,  642.43333333,  647.03333333,
         616.7       ,  564.46666667,  530.83333333,  515.8       ,
         491.93333333,  480.86666667,  492.9       ,  502.46666667,
         494.06666667,  450.86666667,  437.96666667,  427.06666667],
       [ 944.1       ,  986.9       ,  977.3       ,  917.53333333,
         929.66666667,  901.43333333,  866.3       ,  846.        ,
         826.16666667,  832.2       ,  832.        ,  809.36666667,
         743.5       ,  673.23333333,  725.46666667,  792.33333333,
         789.63333333,  681.3       ,  620.4       ,  585.5       ],
       [ 754.36666667,  749.03333333,  751.86666667,  753.53333333,
         752.1       ,  753.3       ,  758.96666667,  758.33333333,
         740.3       ,  714.53333333,  678.66666667,  641.16666667,
         622.        ,  613.86666667,  622.03333333,  621.8       ,
         615.93333333,  605.2       ,  600.73333333,  584.46666667],
       [ 885.8       ,  899.63333333,  882.26666667,  889.2       ,
         870.96666667,  866.36666667,  850.6       ,  841.76666667,
         814.23333333,  752.1       ,  701.73333333,  646.13333333,
         657.33333333,  683.56666667,  740.36666667,  762.86666667,
         749.53333333,  720.8       ,  704.63333333,  669.96666667],
       [ 774.6       ,  771.53333333,  729.86666667,  710.16666667,
         674.7       ,  610.7       ,  641.56666667,  616.63333333,
         622.6       ,  620.13333333,  611.66666667,  578.33333333,
         579.43333333,  540.43333333,  556.56666667,  535.46666667,
         559.56666667,  594.86666667,  564.        ,  555.26666667],
       [ 695.2       ,  671.03333333,  629.53333333,  630.3       ,
         630.6       ,  644.86666667,  663.86666667,  659.36666667,
         608.46666667,  539.63333333,  502.9       ,  506.93333333,
         538.93333333,  557.6       ,  528.83333333,  537.36666667,
         503.06666667,  509.63333333,  457.23333333,  477.46666667],
       [ 858.4       ,  812.96666667,  780.33333333,  777.9       ,
         784.73333333,  774.03333333,  754.53333333,  744.23333333,
         724.4       ,  716.9       ,  679.56666667,  655.33333333,
         625.3       ,  636.46666667,  626.93333333,  640.46666667,
         615.43333333,  623.6       ,  594.93333333,  572.26666667],
       [ 790.93333333,  778.46666667,  769.16666667,  790.63333333,
         804.13333333,  814.3       ,  801.93333333,  762.3       ,
         755.4       ,  751.2       ,  772.16666667,  731.9       ,
         719.93333333,  704.        ,  723.73333333,  729.53333333,
         733.        ,  719.5       ,  690.3       ,  666.23333333],
       [ 601.06666667,  584.9       ,  552.23333333,  536.7       ,
         541.4       ,  526.2       ,  538.1       ,  541.3       ,
         520.96666667,  499.2       ,  470.46666667,  498.23333333,
         478.76666667,  485.7       ,  445.66666667,  506.26666667,
         515.66666667,  541.9       ,  507.7       ,  476.53333333],
       [ 732.63333333,  725.83333333,  714.96666667,  711.43333333,
         722.8       ,  745.83333333,  772.33333333,  763.33333333,
         750.03333333,  686.53333333,  646.73333333,  625.2       ,
         628.9       ,  629.26666667,  615.13333333,  601.        ,
         588.33333333,  605.8       ,  599.13333333,  628.53333333],
       [ 708.1       ,  692.76666667,  676.03333333,  708.03333333,
         689.53333333,  714.56666667,  713.6       ,  718.46666667,
         694.63333333,  695.46666667,  672.93333333,  677.        ,
         665.6       ,  698.4       ,  683.36666667,  690.9       ,
         666.56666667,  637.66666667,  579.43333333,  570.43333333],
       [ 966.13333333,  988.06666667,  989.1       , 1014.03333333,
         986.43333333, 1070.16666667, 1030.86666667, 1008.96666667,
         905.83333333,  847.5       ,  821.76666667,  796.5       ,
         840.13333333,  832.9       ,  825.13333333,  794.93333333,
         763.6       ,  752.06666667,  752.23333333,  773.06666667],
       [ 531.26666667,  512.        ,  512.26666667,  495.03333333,
         580.66666667,  628.63333333,  649.13333333,  597.        ,
         574.06666667,  544.86666667,  580.73333333,  615.83333333,
         676.56666667,  684.6       ,  675.8       ,  631.46666667,
         595.53333333,  560.4       ,  541.46666667,  550.03333333],
       [ 826.46666667,  791.8       ,  803.9       ,  817.4       ,
         812.7       ,  809.8       ,  800.5       ,  827.73333333,
         797.93333333,  755.43333333,  705.86666667,  673.76666667,
         658.66666667,  650.7       ,  658.46666667,  661.9       ,
         656.66666667,  635.9       ,  612.33333333,  587.43333333],
       [ 506.9       ,  494.73333333,  500.13333333,  498.66666667,
         510.56666667,  510.4       ,  515.23333333,  512.        ,
         519.6       ,  499.6       ,  465.16666667,  433.26666667,
         417.66666667,  420.2       ,  419.46666667,  413.76666667,
         392.43333333,  388.1       ,  378.26666667,  382.56666667],
       [ 825.26666667,  821.23333333,  826.86666667,  814.96666667,
         812.03333333,  773.36666667,  787.93333333,  768.13333333,
         771.06666667,  740.23333333,  712.23333333,  693.33333333,
         691.96666667,  692.13333333,  674.23333333,  651.96666667,
         656.46666667,  645.73333333,  643.        ,  635.26666667],
       [ 581.76666667,  553.46666667,  518.63333333,  499.6       ,
         490.46666667,  511.53333333,  540.3       ,  567.96666667,
         543.46666667,  505.5       ,  463.2       ,  479.1       ,
         499.73333333,  509.73333333,  509.3       ,  509.56666667,
         498.16666667,  493.6       ,  472.8       ,  447.7       ],
       [1079.53333333, 1079.96666667, 1070.46666667, 1056.56666667,
        1089.73333333, 1110.1       , 1121.73333333, 1070.73333333,
        1023.9       ,  997.93333333,  976.        ,  918.53333333,
         917.6       ,  886.93333333,  911.13333333,  882.        ,
         892.43333333,  865.86666667,  877.7       ,  862.23333333],
       [ 766.66666667,  782.26666667,  803.33333333,  810.8       ,
         783.43333333,  769.56666667,  770.1       ,  757.36666667,
         743.53333333,  710.4       ,  681.33333333,  663.3       ,
         660.86666667,  650.56666667,  643.36666667,  642.96666667,
         644.43333333,  638.2       ,  622.26666667,  597.83333333],
       [ 661.6       ,  686.26666667,  709.86666667,  634.8       ,
         620.7       ,  594.23333333,  653.66666667,  649.63333333,
         640.93333333,  623.76666667,  590.16666667,  592.76666667,
         590.3       ,  576.06666667,  575.33333333,  572.93333333,
         558.33333333,  511.46666667,  476.06666667,  473.1       ],
       [ 719.26666667,  725.4       ,  655.03333333,  649.7       ,
         600.43333333,  607.36666667,  614.63333333,  607.03333333,
         600.36666667,  543.83333333,  543.46666667,  512.23333333,
         518.86666667,  509.86666667,  550.26666667,  575.03333333,
         582.26666667,  579.86666667,  539.66666667,  540.4       ],
       [ 644.53333333,  623.9       ,  586.6       ,  612.23333333,
         608.46666667,  641.96666667,  646.86666667,  630.6       ,
         600.7       ,  562.93333333,  563.2       ,  523.26666667,
         520.56666667,  525.26666667,  545.46666667,  551.26666667,
         554.06666667,  579.        ,  580.03333333,  534.53333333],
       [ 520.66666667,  487.56666667,  417.63333333,  476.86666667,
         482.33333333,  544.2       ,  539.83333333,  502.46666667,
         478.3       ,  428.46666667,  456.        ,  425.6       ,
         475.3       ,  458.43333333,  456.76666667,  396.43333333,
         391.96666667,  373.7       ,  355.83333333,  363.4       ],
       [ 675.96666667,  638.2       ,  608.3       ,  575.        ,
         562.33333333,  568.2       ,  562.46666667,  573.03333333,
         553.06666667,  532.66666667,  512.4       ,  483.73333333,
         466.33333333,  439.96666667,  447.4       ,  438.83333333,
         441.7       ,  414.93333333,  421.13333333,  404.63333333],
       [ 678.86666667,  655.83333333,  620.73333333,  622.13333333,
         614.7       ,  624.43333333,  624.5       ,  610.3       ,
         582.16666667,  551.8       ,  531.63333333,  576.13333333,
         566.9       ,  570.23333333,  516.76666667,  545.        ,
         556.33333333,  575.46666667,  557.56666667,  541.13333333],
       [ 644.76666667,  627.03333333,  608.96666667,  620.6       ,
         616.7       ,  607.16666667,  594.7       ,  582.66666667,
         570.03333333,  554.1       ,  533.06666667,  517.1       ,
         500.96666667,  487.        ,  468.9       ,  455.66666667,
         450.1       ,  440.53333333,  433.36666667,  413.3       ],
       [ 910.36666667,  869.66666667,  836.86666667,  853.83333333,
         880.2       ,  879.53333333,  869.2       ,  846.46666667,
         834.83333333,  777.6       ,  737.23333333,  714.8       ,
         714.6       ,  715.1       ,  714.3       ,  722.56666667,
         719.03333333,  698.76666667,  685.33333333,  676.03333333],
       [ 799.96666667,  788.03333333,  769.53333333,  660.16666667,
         649.06666667,  595.53333333,  657.73333333,  652.4       ,
         659.23333333,  637.3       ,  662.1       ,  687.7       ,
         671.06666667,  621.1       ,  633.16666667,  632.8       ,
         596.26666667,  536.06666667,  566.5       ,  605.36666667],
       [ 799.83333333,  789.2       ,  787.33333333,  792.73333333,
         807.33333333,  810.6       ,  813.1       ,  790.83333333,
         783.26666667,  778.86666667,  776.66666667,  774.        ,
         767.        ,  739.83333333,  723.06666667,  720.36666667,
         727.9       ,  720.33333333,  705.26666667,  683.23333333],
       [ 842.1       ,  823.56666667,  792.83333333,  818.9       ,
         818.6       ,  830.8       ,  846.66666667,  818.7       ,
         807.76666667,  774.7       ,  763.8       ,  752.93333333,
         726.33333333,  765.2       ,  747.63333333,  763.7       ,
         737.5       ,  731.06666667,  718.4       ,  660.8       ],
       [ 570.13333333,  564.93333333,  561.26666667,  570.03333333,
         575.03333333,  578.23333333,  585.16666667,  564.1       ,
         534.23333333,  501.73333333,  474.16666667,  488.96666667,
         491.03333333,  513.66666667,  503.96666667,  488.96666667,
         485.86666667,  448.36666667,  454.63333333,  419.93333333],
       [ 733.13333333,  740.2       ,  745.3       ,  750.43333333,
         741.4       ,  753.93333333,  768.2       ,  768.73333333,
         749.36666667,  736.96666667,  705.7       ,  697.06666667,
         671.73333333,  650.7       ,  618.73333333,  602.73333333,
         608.5       ,  604.06666667,  595.73333333,  574.96666667],
       [ 639.03333333,  688.9       ,  705.2       ,  649.66666667,
         634.23333333,  615.53333333,  691.86666667,  664.76666667,
         665.93333333,  655.43333333,  666.73333333,  672.83333333,
         646.36666667,  580.13333333,  546.3       ,  523.        ,
         578.7       ,  559.26666667,  562.06666667,  495.26666667],
       [ 947.76666667,  903.53333333,  885.03333333,  904.43333333,
         919.63333333,  931.        ,  902.73333333,  847.7       ,
         788.86666667,  745.4       ,  717.2       ,  734.13333333,
         717.06666667,  694.23333333,  674.8       ,  678.43333333,
         677.26666667,  686.16666667,  688.9       ,  689.43333333],
       [ 753.03333333,  669.43333333,  717.73333333,  742.83333333,
         761.46666667,  768.93333333,  711.73333333,  750.23333333,
         734.76666667,  747.03333333,  669.        ,  742.73333333,
         727.7       ,  714.1       ,  656.06666667,  597.43333333,
         658.16666667,  609.3       ,  670.83333333,  643.83333333],
       [ 877.93333333,  927.86666667,  923.7       ,  928.66666667,
         921.13333333,  907.23333333,  902.36666667,  867.43333333,
         838.03333333,  814.4       ,  785.9       ,  759.03333333,
         721.93333333,  712.03333333,  701.        ,  717.96666667,
         727.46666667,  727.96666667,  717.56666667,  678.13333333],
       [ 625.6       ,  627.03333333,  645.06666667,  661.9       ,
         671.36666667,  663.96666667,  668.5       ,  654.96666667,
         643.9       ,  629.86666667,  595.1       ,  579.96666667,
         569.4       ,  590.73333333,  590.93333333,  581.5       ,
         565.4       ,  550.4       ,  545.66666667,  534.8       ],
       [ 521.53333333,  547.46666667,  536.83333333,  550.03333333,
         513.63333333,  518.86666667,  515.63333333,  528.66666667,
         527.06666667,  510.26666667,  524.23333333,  511.66666667,
         526.1       ,  506.2       ,  509.        ,  512.36666667,
         531.93333333,  536.8       ,  529.16666667,  520.73333333],
       [ 581.83333333,  529.7       ,  496.6       ,  471.53333333,
         546.2       ,  573.86666667,  590.73333333,  520.46666667,
         531.5       ,  506.96666667,  523.06666667,  463.6       ,
         462.46666667,  448.93333333,  449.23333333,  415.13333333,
         414.4       ,  471.36666667,  454.7       ,  417.13333333],
       [ 750.13333333,  751.        ,  769.83333333,  771.83333333,
         776.6       ,  761.76666667,  776.9       ,  755.66666667,
         756.5       ,  719.06666667,  712.86666667,  680.06666667,
         652.5       ,  615.16666667,  596.26666667,  586.16666667,
         589.1       ,  578.16666667,  576.8       ,  567.03333333],
       [ 542.26666667,  562.66666667,  571.33333333,  565.46666667,
         544.83333333,  514.66666667,  492.4       ,  503.63333333,
         507.23333333,  495.03333333,  460.7       ,  471.63333333,
         469.2       ,  471.23333333,  458.7       ,  454.63333333,
         429.13333333,  415.56666667,  411.16666667,  429.3       ],
       [ 756.86666667,  804.53333333,  786.83333333,  793.53333333,
         761.66666667,  762.33333333,  763.2       ,  739.36666667,
         757.        ,  754.93333333,  734.13333333,  722.26666667,
         735.86666667,  743.26666667,  722.63333333,  699.26666667,
         695.33333333,  708.66666667,  683.06666667,  701.1       ],
       [ 695.26666667,  693.03333333,  687.13333333,  649.5       ,
         645.2       ,  643.66666667,  658.86666667,  666.16666667,
         650.66666667,  627.7       ,  600.06666667,  587.36666667,
         601.46666667,  586.13333333,  588.1       ,  595.2       ,
         615.36666667,  626.1       ,  608.06666667,  589.73333333],
       [ 653.33333333,  651.6       ,  617.36666667,  718.7       ,
         723.83333333,  772.4       ,  719.76666667,  719.93333333,
         668.9       ,  644.23333333,  626.43333333,  609.23333333,
         544.7       ,  542.83333333,  537.66666667,  550.4       ,
         478.5       ,  480.16666667,  546.93333333,  567.73333333]])

In [15]:
treat_index

[24,
 15,
 13,
 13,
 13,
 13,
 13,
 13,
 24,
 24,
 13,
 19,
 13,
 14,
 13,
 24,
 13,
 16,
 18,
 13,
 13,
 13,
 13,
 24,
 21,
 15,
 20,
 13,
 14,
 13,
 13,
 13,
 13,
 13,
 13,
 21,
 13,
 14,
 13,
 24,
 23,
 24,
 24,
 19,
 13,
 18,
 13,
 13,
 24,
 24]

In [14]:
adopt_year

0     2025
1     2016
2     2014
3     2014
4     2014
5     2014
6     2014
7     2014
8     2025
9     2025
10    2014
11    2020
12    2014
13    2015
14    2014
15    2025
16    2014
17    2017
18    2019
19    2014
20    2014
21    2014
22    2014
23    2025
24    2022
25    2016
26    2021
27    2014
28    2015
29    2014
30    2014
31    2014
32    2014
33    2014
34    2014
35    2022
36    2014
37    2015
38    2014
39    2025
40    2024
41    2025
42    2025
43    2020
44    2014
45    2019
46    2014
47    2014
48    2025
49    2025
Name: ADOPTION, dtype: int64